# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='prog2',
            field=models.BooleanField(default=False),
        ),
    ]
