# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runjobs', '0003_auto_20160117_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fake_infile',
            field=models.CharField(default='NO_INPUT', max_length=100),
        ),
    ]
