# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newspost',
            name='text',
            field=models.TextField(default='BLANK POST'),
        ),
    ]
